services:
  mariadb:
    image: mariadb:10.11
    container_name: stock_dashboard_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my_secure_password
      MYSQL_DATABASE: stock_dashboard
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - stock_net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock_dashboard_backend
    restart: always
    depends_on:
      - mariadb
    environment:
      DATABASE_URL: "mysql+aiomysql://root:my_secure_password@mariadb:3306/stock_dashboard"
    ports:
      - "8000:8000"
    networks:
      - stock_net

volumes:
  mariadb_data:
    driver: local

networks:
  stock_net: